# Generated by Django 3.1.4 on 2020-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='consolidated',
            field=models.BooleanField(default=False),
        ),
    ]
